---
- name: redis-server
  apt:
    name: redis-server
    state: present
  notify: redis needs to be started

- name: redis-tools
  apt:
    name: redis-tools
    state: present

- name: listen on all interfaces
  lineinfile:
    dest: "/etc/redis/redis.conf"
    line: "bind 0.0.0.0 ::0"
    regexp: "^bind .+"
  notify: redis needs to be started

- name: maxmemory
  lineinfile:
    dest: "/etc/redis/redis.conf"
    line: "maxmemory {{ (ansible_memtotal_mb - 256) * 1024 * 1024 }}"
    insertafter: "^# maxmemory"
    regexp: "^maxmemory .+"
  notify: redis needs to be started

- name: password
  lineinfile:
    dest: "/etc/redis/redis.conf"
    line: "requirepass {{ redis_password }}"
    insertafter: "^# requirepass"
    regexp: "^requirepass .+"
  notify: redis needs to be started

- name: enabled AOF persistence
  lineinfile:
    dest: "/etc/redis/redis.conf"
    line: "appendonly yes"
    insertafter: "^# appendonly"
    regexp: "^appendonly .+"
  notify: redis needs to be started
