---
- name: Remove postgresql 10 client
  ansible.builtin.apt:
    name: postgresql-client-10
    state: absent

- name: Apt gpg key for postgresql
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Apt repository for postgresql
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main

- name: Update Aptitude cache
  ansible.builtin.apt:
    update_cache: true"

- name: Package postgresql-client-13
  ansible.builtin.apt:
    name: postgresql-client-13
    state: latest
