- name: config file
  template:
    src: newrelic-infra.yml
    dest: /etc/newrelic-infra.yml
    owner: root
    mode: 0644
  notify: Restart New Relic Infrastructure Agent

- name: New Relic APT key
  when: ansible_distribution == "Ubuntu"
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name: New Relic APT repo
  when: ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ansible_distribution_release}} main"
    state: present
    filename: newrelic-infra
    update_cache: yes
    # cache_valid_time: 3600

- name: New Relic Infrastructure Agent
  when: ansible_distribution == "Ubuntu"
  apt:
    name: newrelic-infra
    state: latest
  notify: Restart New Relic Infrastructure Agent
