# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role

- hosts: all
  sudo: true
  roles:
    - groups
    - users
    - base
    - general
- include: web.yml
