---
- name: "Command for {{ app.name }}"
  template:
    src: app.sh
    dest: "/usr/local/bin/{{ app.name }}"
    owner: root
    group: root
    mode: "0755"

- name: App environment
  template:
    src: app-env.sh
    dest: /home/{{ app.name }}/.app-env.sh
    owner: root
    group: root
    mode: "0644"

- name: App environment in .bashrc
  lineinfile:
    dest: "/home/{{ app.name }}/.bashrc"
    line: ". ~/.app-env.sh"
    insertbefore: "If not running interactively, don't do anything"
  # In fact, it's incredibly important for Capistrano that this file be run regardless of
  # whether the session is interactive.

- name: "'cd' in .bashrc"
  lineinfile:
    dest: "/home/{{ app.name }}/.bashrc"
    line: "cd /var/www/{{ app.name }}/current"
