---
- name: Group webapps
  ansible.builtin.group:
    name: webapps
    gid: 600
    state: present

- name: "User {{ app.name }}"
  ansible.builtin.user:
    name: "{{ app.name }}"
    shell: /bin/bash
    group: webapps
    state: present

- name: "Home directory for {{ app.name }}"
  ansible.builtin.file:
    path: "/home/{{ app.name }}"
    state: directory
    owner: "{{ app.name }}"
    group: webapps
    mode: u=rwx,g=rwx,o=

- name: "SSH config directory for {{ app.name }}"
  ansible.builtin.file:
    path: "/home/{{ app.name }}/.ssh"
    state: directory
    owner: "{{ app.name }}"
    group: webapps

# This is optional. If set, it's used by the application when it uses SSH to connect outward.
- name: "SSH key for {{ app.name }}"
  ansible.builtin.copy:
    dest: "/home/{{ app.name }}/.ssh/id_rsa"
    content: "{{ app.ssh_key.private }}"
    mode: "0600"
  when: app.ssh_key is defined and app.ssh_key.private is defined
