---
- name: Enable minecraft service
  become: true
  ansible.builtin.shell: systemctl daemon-reload; systemctl enable minecraft.service

- name: Restart minecraft service
  become: true
  ansible.builtin.shell: systemctl restart minecraft.service

- name: Restart Apache server
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted
  ignore_errors: true
