- name: required packages
  apt:
    name: jq
    state: latest

- name: JDK PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
    update_cache: yes

- name: JDK
  become: true
  apt:
    name: openjdk-8-jre-headless
    state: present

- name: correct java version
  become: true
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: download Minecraft launcher manifest
  get_url:
    url: https://launchermeta.mojang.com/mc/game/version_manifest.json
    dest: /tmp/minecraft_version_manifest.json
    force: yes

- name: get Minecraft version
  shell: "jq -r '.latest.release' /tmp/minecraft_version_manifest.json"
  register: minecraft_version

- name: minecraft group
  group:
    name: minecraft
    gid: 700

- name: minecraft user
  user:
    name: minecraft
    group: minecraft
    shell: /bin/false
    uid: 700
    createhome: yes

- name: Minecraft folder
  file:
    dest: /var/minecraft
    state: directory
    owner: minecraft
    group: minecraft

- name: Minecraft Server JAR
  get_url:
    url: https://s3.amazonaws.com/Minecraft.Download/versions/{{minecraft_version.stdout}}/minecraft_server.{{minecraft_version.stdout}}.jar
    dest: /var/minecraft/minecraft_server_{{minecraft_version.stdout}}.jar
    mode: u=rw,g=rw,o=r
    owner: root
  notify: restart minecraft service

- name: Minecraft client folder
  file:
    dest: /var/minecraft/client/{{minecraft_version.stdout}}
    recurse: yes
    state: directory
    owner: root
    group: root

- name: Minecraft client JAR
  get_url:
    url: https://s3.amazonaws.com/Minecraft.Download/versions/{{minecraft_version.stdout}}/{{minecraft_version.stdout}}.jar
    dest: /var/minecraft/client/{{minecraft_version.stdout}}/{{minecraft_version.stdout}}.jar
    mode: u=rw,g=rw,o=r
    owner: root

- name: Minecraft systemd service
  template:
    src: minecraft.systemd.conf
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: 0664
  notify: enable minecraft service
