---
- name: Required packages
  ansible.builtin.apt:
    name: jq
    state: latest

- name: JDK PPA
  ansible.builtin.apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
    update_cache: true

- name: JDK
  become: true
  ansible.builtin.apt:
    name: openjdk-8-jre-headless
    state: present

- name: Correct java version
  become: true
  ansible.builtin.alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: Download Minecraft launcher manifest
  ansible.builtin.get_url:
    url: https://launchermeta.mojang.com/mc/game/version_manifest.json
    dest: /tmp/minecraft_version_manifest.json
    force: true

- name: Get Minecraft version
  # When you want a specific version of Minecraft
  # shell: "echo '1.7.10'"
  ansible.builtin.shell: "jq -r '.latest.release' /tmp/minecraft_version_manifest.json"
  register: minecraft_version

- name: Get Minecraft launcher data URL
  ansible.builtin.shell: 'jq -r ''.versions[] | select(.id =="{{ minecraft_version.stdout }}") | .url'' /tmp/minecraft_version_manifest.json'
  register: minecraft_launcher_data_url

- name: Download Minecraft launcher data
  ansible.builtin.get_url:
    url: "{{ minecraft_launcher_data_url.stdout }}"
    dest: "/tmp/minecraft_launcher_data_{{ minecraft_version.stdout }}.json"
    force: true

- name: Get Minecraft server URL
  ansible.builtin.shell: "jq -r '.downloads.server.url' /tmp/minecraft_launcher_data_{{ minecraft_version.stdout }}.json"
  register: minecraft_server_url

- name: Get Minecraft server SHA
  ansible.builtin.shell: "jq -r '.downloads.server.sha1' /tmp/minecraft_launcher_data_{{ minecraft_version.stdout }}.json"
  register: minecraft_server_sha

- name: Get Minecraft client URL
  ansible.builtin.shell: "jq -r '.downloads.client.url' /tmp/minecraft_launcher_data_{{ minecraft_version.stdout }}.json"
  register: minecraft_client_url

- name: Get Minecraft client SHA
  ansible.builtin.shell: "jq -r '.downloads.client.sha1' /tmp/minecraft_launcher_data_{{ minecraft_version.stdout }}.json"
  register: minecraft_client_sha

- name: minecraft group
  ansible.builtin.group:
    name: minecraft
    gid: 700

- name: minecraft user
  ansible.builtin.user:
    name: minecraft
    group: minecraft
    ansible.builtin.shell: /bin/false
    uid: 700
    createhome: true

- name: Minecraft folder
  ansible.builtin.file:
    dest: /var/minecraft
    state: directory
    owner: minecraft
    group: minecraft

- name: Minecraft Server JAR
  ansible.builtin.get_url:
    url: "{{ minecraft_server_url.stdout }}"
    checksum: "sha1:{{ minecraft_server_sha.stdout }}"
    dest: /var/minecraft/minecraft_server_{{ minecraft_version.stdout }}.jar
    mode: u=rw,g=rw,o=r
    owner: root
  notify: restart minecraft service

- name: Minecraft client folder
  ansible.builtin.file:
    dest: /var/minecraft/client/{{minecraft_version.stdout}}
    recurse: true
    state: directory
    owner: root
    group: root

- name: Minecraft client JAR
  ansible.builtin.get_url:
    url: "{{ minecraft_client_url.stdout }}"
    checksum: "sha1:{{ minecraft_client_sha.stdout }}"
    dest: /var/minecraft/client/{{minecraft_version.stdout}}/{{minecraft_version.stdout}}.jar
    mode: u=rw,g=rw,o=r
    owner: root

- name: Minecraft systemd service
  ansible.builtin.template:
    src: minecraft.systemd.conf
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: "0664"
  notify: enable minecraft service
