- name: Fail2ban needs to be started
  ansible.builtin.service:
    name: fail2ban
    state: started

- name: Rsyslog needs to be reloaded
  ansible.builtin.service:
    name: rsyslog
    state: restarted
