---
- import_tasks: rbenv.yml
- include_tasks: "{{ app.ruby_version }}.yml"

- import_tasks: nodenv.yml
  when: app.node_version is defined
- include_tasks: "node_{{ app.node_version }}.yml"
  when: app.node_version is defined
- import_tasks: nodejs_10.yml
  when: app.node_version is not defined

- import_tasks: user.yml
- import_tasks: app_folders.yml
- import_tasks: app_deploy_user.yml
- import_tasks: app_command.yml
- import_tasks: logrotate.yml
- include_tasks: secret_files.yml
  when: app.secret_files is defined

- include_tasks: nginx_virtual_host.yml
  when: ruby_app_web is defined and ruby_app_web
- include_tasks: systemd_web.yml
  when: ruby_app_web is defined and ruby_app_web

- include_tasks: systemd_background.yml
  when: ruby_app_worker is defined and ruby_app_worker and app.app_has_background_processes
