- name: webapps group
  group: name=webapps gid=600 state=present

- name: "{{ app_name }} user"
  user: name={{ app_name }} shell=/bin/bash group=webapps state=present

- name: directory /var/www/{{ app_name }}
  file: path=/var/www/{{ app_name }} state=directory group=webapps owner={{ app_name }} recurse=yes

- name: directory /var/www/{{ app_name }}/shared
  file: path=/var/www/{{ app_name }}/shared state=directory group=webapps owner={{ app_name }} recurse=yes

- name: "{{ app_name }} .ssh directory"
  file: path=/home/{{ app_name }}/.ssh state=directory group=webapps owner={{ app_name }} recurse=yes
