---
- name: webapps group
  group: name=webapps gid=600 state=present

- name: "{{ app.name }} user"
  user: name={{ app.name }} shell=/bin/bash group=webapps state=present

- name: directory /var/www/{{ app.name }}
  file: path=/var/www/{{ app.name }} state=directory group=webapps owner={{ app.name }} recurse=yes

- name: directory /var/www/{{ app.name }}/shared
  file: path=/var/www/{{ app.name }}/shared state=directory group=webapps owner={{ app.name }} recurse=yes

- name: "{{ app.name }} .ssh directory"
  file: path=/home/{{ app.name }}/.ssh state=directory group=webapps owner={{ app.name }} recurse=yes
