---
- name: directory /var/www/{{ app.name }}
  ansible.builtin.file:
    path: /var/www/{{ app.name }}
    state: directory
    group: webapps
    owner: "{{ app.name }}"

- name: directory /var/www/{{ app.name }}/shared
  ansible.builtin.file:
    path: /var/www/{{ app.name }}/shared
    state: directory
    group: webapps
    owner: "{{ app.name }}"
