
- name: "create {{ app_to_deploy }} command"
  template:
    src: app.sh
    dest: "/usr/local/bin/{{ app_to_deploy }}"
    owner: root
    group: root
    mode: 0755

- name: "add 'cd' to the app .bashrc"
  lineinfile:
    dest: "/home/{{ app_to_deploy }}/.bashrc"
    line: "cd /var/www/{{ app_to_deploy }}/current"
