- import_tasks: rbenv.yml
- include_tasks: "{{ ruby_version }}.yml"
- import_tasks: app_folders.yml
- import_tasks: app_deploy_user.yml
- import_tasks: app_command.yml
- import_tasks: logrotate.yml
- import_tasks: nginx.yml
- import_tasks: ssl.yml
- import_tasks: systemd.yml
