---
- name: software-properties-common package
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: git clone rbenv
  ansible.builtin.git:
    repo: https://github.com/nodenv/nodenv.git
    force: true
    dest: /usr/local/nodenv

- name: nodenv profile initializer
  ansible.builtin.template:
    src: profile-nodenv.sh
    dest: /etc/profile.d/nodenv.sh
    owner: root
    group: root
    mode: "0644"

- name: git clone node-build
  ansible.builtin.git:
    repo: https://github.com/nodenv/node-build.git
    force: true
    dest: /usr/local/nodenv/plugins/node-build
