---
- name: detect existing Node 14.16.0
  ansible.builtin.comment: /usr/local/nodenv/versions/14.16.0/bin/node --version 2>&1 | grep "14.16.0"
  register: existing_node
  ignore_errors: true

- name: install Node 14.16.0
  ansible.builtin.shell: NODENV_ROOT=/usr/local/nodenv /usr/local/nodenv/bin/nodenv install 14.16.0
  register: installed_node
  when: existing_node.failed

- name: install yarn for Node 14.16.0
  ansible.builtin.shell: NODENV_ROOT=/usr/local/nodenv NODENV_VERSION=14.16.0 /usr/local/nodenv/bin/nodenv exec npm install -g yarn
  when: installed_node.changed
