---
- name: apt gpg key for node
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: apt gpg key for yarn
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: apt repository for node
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_10.x bionic main

- name: apt src repository for node
  ansible.builtin.apt_repository:
    repo: deb-src https://deb.nodesource.com/node_10.x bionic main

- name: apt repository for yarn
  ansible.builtin.apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main

- name: update Aptitude cache
  ansible.builtin.apt:
    update_cache: true

- name: node.js and yarn
  ansible.builtin.apt:
    name:
    - nodejs
    - yarn
    state: present
