---
- name: software-properties-common package
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: git clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    force: true
    dest: /usr/local/rbenv

- name: rbenv profile initializer
  template:
    src: profile-rbenv.sh
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root
    mode: "0644"

- name: git clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    force: true
    dest: /usr/local/rbenv/plugins/ruby-build
