---
- name: software-properties-common package
  apt:
    name: software-properties-common
    state: present

- name: git clone rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /usr/local/rbenv

- name: rbenv profile initializer
  template: src=profile-rbenv.sh dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0644

- name: git clone ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build
