- name: install packages required for Ruby 2.2.3
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items:
   - libreadline-dev

- name: detect existing Ruby 2.2.3
  command: /usr/local/rbenv/versions/2.2.3/bin/ruby --version 2>&1 | grep "ruby 2.2.3"
  register: existing_mri
  ignore_errors: True

- name: install Ruby 2.2.3
  shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv install 2.2.3
  register: installed_mri
  when: existing_mri|failed

- name: update Rubygems for Ruby 2.2.3
  shell: RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.2.3 /usr/local/rbenv/bin/rbenv exec gem update --system
  when: installed_mri.changed

- name: install bundler for Ruby 2.2.3
  shell: RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.2.3 /usr/local/rbenv/bin/rbenv exec gem install bundler
  when: installed_mri.changed
