---
- name: detect existing Ruby 3.0.3
  command: /usr/local/rbenv/versions/3.0.3/bin/ruby --version 2>&1 | grep "ruby 3.0.3"
  register: existing_mri
  ignore_errors: true

- name: install packages required for Ruby 3.0.3
  apt:
    name:
    - libreadline-dev
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libpq-dev
    state: latest
  when: existing_mri.failed

- name: install Ruby 3.0.3
  shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv install 3.0.3
  register: installed_mri
  when: existing_mri.failed

- name: update Rubygems for Ruby 3.0.3
  shell: RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=3.0.3 /usr/local/rbenv/bin/rbenv exec gem update --system
  when: installed_mri.changed
