---
- name: detect existing Ruby 2.7.0
  ansible.builtin.comment: /usr/local/rbenv/versions/2.7.0/bin/ruby --version 2>&1 | grep "ruby 2.7.0"
  register: existing_mri
  ignore_errors: true

- name: install packages required for Ruby 2.7.0
  ansible.builtin.apt:
    name:
    - libreadline-dev
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libpq-dev
    state: latest
  when: existing_mri.failed

- name: install Ruby 2.7.0
  ansible.builtin.shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv install 2.7.0
  register: installed_mri
  when: existing_mri.failed

- name: update Rubygems for Ruby 2.7.0
  ansible.builtin.shell: RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.7.0 /usr/local/rbenv/bin/rbenv exec gem update --system
  when: installed_mri.changed
