---
- name: web server service
  template:
    src: systemd-web.conf 
    dest: /etc/systemd/system/{{ app.name }}.service
    owner: root
    group: root
    mode: 0644
  register: web_service

- name: web server restarter service
  template:
    src: systemd-web-restarter.conf 
    dest: /etc/systemd/system/{{ app.name }}-restart.service
    owner: root
    group: root
    mode: 0644
  register: web_service_restarter

- name: web server restarter activator
  template:
    src: systemd-web-restarter-path.conf 
    dest: /etc/systemd/system/{{ app.name }}-restart.path
    owner: root
    group: root
    mode: 0644
  register: web_service_restarter_activator

- name: reload system daemons
  systemd:
    daemon_reload: yes
  when: web_service.changed or web_service_restarter.changed or web_service_restarter_activator.changed

- name: restart web server
  systemd:
    name: "{{ app.name }}.service"
    enabled: yes
    state: restarted
  when: web_service.changed

- name: restart web server restart trigger
  systemd:
    name: "{{ app.name }}-restart.path"
    enabled: yes
    state: restarted
  when: web_service_restarter_activator.changed
