---
- name: web server service
  ansible.builtin.template:
    src: systemd-web.conf
    dest: /etc/systemd/system/{{ app.name }}.service
    owner: root
    group: root
    mode: "0644"
  register: web_service

- name: web server restarter service
  ansible.builtin.template:
    src: systemd-web-restarter.conf
    dest: /etc/systemd/system/{{ app.name }}-restart.service
    owner: root
    group: root
    mode: "0644"
  register: web_service_restarter

- name: web server restarter activator
  ansible.builtin.template:
    src: systemd-web-restarter-path.conf
    dest: /etc/systemd/system/{{ app.name }}-restart.path
    owner: root
    group: root
    mode: "0644"
  register: web_service_restarter_activator

- name: reload system daemons
  ansible.builtin.systemd:
    daemon_reload: true
  when: web_service.changed or web_service_restarter.changed or web_service_restarter_activator.changed

- name: restart web server
  ansible.builtin.systemd:
    name: "{{ app.name }}.service"
    enabled: true
    state: restarted
  when: web_service.changed

- name: restart web server restart trigger
  ansible.builtin.systemd:
    name: "{{ app.name }}-restart.path"
    enabled: true
    state: restarted
  when: web_service_restarter_activator.changed
