---
- name: app service
  template:
    src: systemd-app.conf 
    dest: /etc/systemd/system/{{app_name}}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - system daemons should be reloaded
    - app should be restarted
