---
- name: web server service
  template:
    src: systemd-web.conf 
    dest: /etc/systemd/system/{{app_name}}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - system daemons should be reloaded
    - web server should be restarted

- name: web server restarter service
  template:
    src: systemd-web-restarter.conf 
    dest: /etc/systemd/system/{{app_name}}-restart.service
    owner: root
    group: root
    mode: 0644
  notify:
    - system daemons should be reloaded

- name: web server restarter activator
  template:
    src: systemd-web-restarter-path.conf 
    dest: /etc/systemd/system/{{app_name}}-restart.path
    owner: root
    group: root
    mode: 0644
  notify:
    - system daemons should be reloaded
    - web server restart trigger should be started
