---
- name: Disable SSH password login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "PasswordAuthentication (yes|no)"
  notify:
    - SSHd needs to be restarted

- name: Enable SSH TCPKeepAlive
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: "TCPKeepAlive yes"
    regexp: "TCPKeepAlive (yes|no)"
  notify:
    - SSHd needs to be restarted

- name: Enable SSH PermitUserEnvironment
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitUserEnvironment yes"
    regexp: "PermitUserEnvironment (yes|no)"
  notify:
    - SSHd needs to be restarted

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: "PermitRootLogin (yes|no)"
  notify:
    - SSHd needs to be restarted
