---
- name: nginx should be reloaded
  # reloading the service always fails, so we're restarting instead
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: nginx should be restarted
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: sysctl should be reloaded
  ansible.builtin.shell: sysctl -p

- name: rsyslog should be reloaded
  ansible.builtin.service:
    name: rsyslog
    state: restarted
