---
- name: Postgres client for Finch Staging
  hosts: astro-production
  become: true
  vars:
    postgresql_version: 15
  roles:
    - ome.postgresql_client
- name: Finch Staging
  hosts: finch-staging
  become: true
  vars_files:
    - vars/finch_staging.yml
  roles:
    - nginx
    - ruby_app
