
- hosts: finch
  become: true
  vars_files:
    - vars/finch.yml
  roles:
    - nginx
    - role: ruby_app
      ruby_version: 'ruby_2.4.3'
      app_name: 'finch'
      app_web_name: 'finch.rndsvc.net'
      app_local_port: 9282
