---
- hosts: finch-production
  become: true
  vars_files:
    - vars/finch_production.yml
  roles:
    - nginx
    - postgresql_client
    - ruby_app
- hosts: finch-production-redis
  become: true
  vars_files:
    - vars/finch_production.yml
  roles:
    - redis
