---
- name: Postgres client for Finch Production
  hosts: astro-production
  become: true
  vars:
    postgresql_version: 15
  roles:
    - ome.postgresql_client
- name: Finch Production
  hosts: finch-production
  become: true
  vars_files:
    - vars/finch_production.yml
  roles:
    - nginx
    - ruby_app
