---
- name: Docker
  hosts: forgejo
  become: true
  roles:
    - geerlingguy.docker
  vars_files:
    - vars/forgejo.yml
  vars:
    docker_install_compose: true
    docker_users:
      - robind
- name: Forgejo
  hosts: forgejo
  become: true
  roles:
    - forgejo
  vars_files:
    - vars/forgejo.yml
