---
- name: Postgresql server
  hosts: forgejo
  become: true
  roles:
    - geerlingguy.postgresql
  vars_files:
    - vars/forgejo.yml
  vars:
    postgresql_version: 17
    postgresql_databases:
      - name: forgejo
        owner: forgejo
    postgresql_users:
      - name: forgejo
        password: "{{ forgejo_db_password }}"
        login_host: localhost
- name: Docker
  hosts: forgejo
  become: true
  roles:
    - geerlingguy.docker
  vars_files:
    - vars/forgejo.yml
  vars:
    docker_install_compose: true
    docker_users:
      - robind
- name: Forgejo
  hosts: forgejo
  become: true
  roles:
    - forgejo
  vars_files:
    - vars/forgejo.yml
