---
# Used only for initial setup, which is why the `root` user is specified.
- name: Initial setup
  hosts: all
  remote_user: root
  roles:
    - upgrade
    - common
    - hostname
    - groups
    - users
    - ssh
