
- hosts: releasemaker
  become: true
  vars_files:
    - vars/releasemaker_staging.yml
  roles:
    - nginx
    - role: ruby_app
      ruby_version: 'ruby_2.4.3'
      app_name: 'releasemaker_staging'
      app_has_background_processes: false
      app_web_name: 'staging.releasemaker.com'
