
- hosts: releasemaker
  become: true
  roles:
    - nginx
    -
      role: ruby_app
      ruby_version: 'ruby_2.4.3'
      app_to_deploy: 'releasemaker'
      web_hostnames: 'www.releasemaker.com releasemaker.com'
      app_local_port: 9292
