---
- name: Postgres client for Releasemaker Staging
  hosts: astro-production
  become: true
  vars:
    postgresql_version: 15
  roles:
    - ome.postgresql_client
- name: Releasemaker Staging
  hosts: releasemaker-staging
  become: true
  vars_files:
    - vars/releasemaker_staging.yml
  roles:
    - nginx
    - ruby_app
