---
- name: Postgres client for Releasemaker Production
  hosts: astro-production
  become: true
  vars:
    postgresql_version: 15
  roles:
    - ome.postgresql_client
- name: Releasemaker Production
  hosts: releasemaker-production
  become: true
  vars_files:
    - vars/releasemaker_production.yml
  roles:
    - nginx
    - ruby_app
