---
# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role
- name: General
  hosts: all
  become: true
  roles:
    - hostname
    - common
    - ssh
    - fail2ban
    - groups
    - users
- name: Finch Production
  ansible.builtin.import_playbook: finch_production.yml
- name: Finch Staging
  ansible.builtin.import_playbook: finch_staging.yml
- name: Releasemaker Production
  ansible.builtin.import_playbook: releasemaker_production.yml
- name: Releasemaker Staging
  ansible.builtin.import_playbook: releasemaker_staging.yml
- name: SarahMakesStuff website
  ansible.builtin.import_playbook: sarahmakesstuff-web.yml
- name: Minecraft
  ansible.builtin.import_playbook: minecraft.yml
