---
# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role
- hosts: all
  become: true
  roles:
    - hostname
    - common
    - role: logdna.logdna
      conf_key: "{{ logdna_ingestion_key }}"
    - logdna_config
    - ssh
    - fail2ban
    - groups
    - users
- import_playbook: redis.yml
- import_playbook: finch_production.yml
- import_playbook: finch_staging.yml
- import_playbook: releasemaker_production.yml
- import_playbook: releasemaker_staging.yml
- import_playbook: minecraft.yml
