# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role

- hosts: all
  become: true
  roles:
    - hostname
    - common
    - ssh
    - newrelic_infra
    - fail2ban
    - groups
    - users
- import_playbook: finch_staging.yml
- import_playbook: releasemaker.yml
- import_playbook: robindaugherty-web.yml
- import_playbook: minecraft.yml
