# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role

- hosts: all
  become: true
  roles:
    - hostname
    - common
    - ssh
    - newrelic_infra
    - fail2ban
    - groups
    - users
- include: web.yml
- include: minecraft.yml
