---
# http://docs.ansible.com/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role
- name: General
  hosts: all
  become: true
  roles:
    - hostname
    - common
    - ssh
    - fail2ban
    - groups
    - users
- name: Redis
  import_playbook: redis.yml
- name: Finch Production
  import_playbook: finch_production.yml
- name: Finch Staging
  import_playbook: finch_staging.yml
- name: Releasemaker Production
  import_playbook: releasemaker_production.yml
- name: Releasemaker Staging
  import_playbook: releasemaker_staging.yml
- name: Minecraft
  import_playbook: minecraft.yml
