- name: Update Aptitude cache
  ansible.builtin.apt:
    update_cache: true

- name: Aptitude
  ansible.builtin.apt:
    pkg: aptitude
    state: latest

- name: Upgrade Aptitude packages
  ansible.builtin.apt:
    upgrade: full
