---
- name: "Per-user group for {{ item.username }}"
  ansible.builtin.group:
    name: "{{ item.username }}"
    gid: "{{ item.uid }}"
  when: users_create_per_user_group

- name: "Create/Update {{ item.username }}"
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.username  if users_create_per_user_group else users_group}}"
    groups: "{{ item.groups  | join(',')}}"
    shell: "{{ item.shell  if item.shell is defined else users_default_shell}}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    createhome: "{{'yes' if users_create_homedirs else 'no'}}"
    password: "{{ item.password }}"

- name: "Clone oh-my-zsh repo for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ item.username }}/.oh-my-zsh"

- name: "Look for existing .zshrc for {{ item.username }}"
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/.zshrc"
  register: zshrc

- name: "Copy .zshrc from oh-my-zsh for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.command: "cp -a /home/{{ item.username }}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{ item.username }}/.zshrc"
  when: zshrc.stat.exists == false

- name: "Custom themes directory for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.oh-my-zsh/custom/themes"
    state: directory
    recurse: yes

- name: "Theme for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/RobinDaugherty/robind-zsh-theme/master/robind.zsh-theme
    dest: "/home/{{ item.username }}/.oh-my-zsh/custom/themes/robind.zsh-theme"
    mode: "0664"

- name: "remove old robind zsh theme for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.file:
    dest: "/home/{{ item.username }}/.oh-my-zsh/themes/robind.zsh-theme"
    state: absent

- name: "zsh theme preference for {{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.lineinfile:
    dest: "/home/{{ item.username }}/.zshrc"
    line: ZSH_THEME="robind"
    regexp: "ZSH_THEME="

- name: "authorized SSH keys for {{ item.username }}"
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key  | join('\n')}}"
    exclusive: true
