- name: Per-user group
  group:
    name: "{{item.username}}"
    gid: "{{item.uid}}"
  when: users_create_per_user_group

- name: Create/Update Users
  user:
    name: "{{item.username}}"
    group: "{{item.username if users_create_per_user_group else users_group}}"
    groups: "{{item.groups | join(',')}}"
    shell: "{{item.shell if item.shell is defined else users_default_shell}}"
    comment: "{{item.name}}"
    uid: "{{item.uid}}"
    createhome: "{{'yes' if users_create_homedirs else 'no'}}"
    password: "{{item.password}}"

- name: Clone oh-my-zsh repo
  become: true
  become_user: "{{item.username}}"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{item.username}}/.oh-my-zsh"

- name: Look for existing .zshrc
  stat:
    path: "/home/{{item.username}}/.zshrc"
  register: zshrc

- name: Copy .zshrc from oh-my-zsh
  become: true
  become_user: "{{item.username}}"
  command: "cp -a /home/{{item.username}}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{item.username}}/.zshrc" 
  when: zshrc.stat.exists == false

- name: custom themes directory
  become: true
  become_user: "{{item.username}}"
  file:
    path: "/home/{{item.username}}/.oh-my-zsh/custom/themes"
    state: directory
    recurse: yes

- name: Add robind zsh theme
  become: true
  become_user: "{{item.username}}"
  get_url:
    url: https://raw.githubusercontent.com/RobinDaugherty/robind-zsh-theme/master/robind.zsh-theme
    dest: "/home/{{item.username}}/.oh-my-zsh/custom/themes/robind.zsh-theme"
    mode: 0664

- name: Remove old robind zsh theme
  become: true
  become_user: "{{item.username}}"
  file:
    dest: "/home/{{item.username}}/.oh-my-zsh/themes/robind.zsh-theme"
    state: absent

- name: Set zsh theme to robind
  become: true
  become_user: "{{item.username}}"
  lineinfile:
    dest: "/home/{{item.username}}/.zshrc"
    line: ZSH_THEME="robind"
    regexp: "ZSH_THEME="

- name: Add/Update User SSH keys
  authorized_key:
    user: "{{item.username}}"
    key: "{{item.ssh_key.0}}"
