---
- include_vars: "users.yml"

- name: Per-user group creation
  group: name="{{item.username}}" gid="{{item.uid}}"
  with_items: create_users
  when: users_create_per_user_group
  tags: ['users','configuration']

- name: Create/Update Users
  user: name="{{item.username}}"
        group="{{item.username if users_create_per_user_group else users_group}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        comment="{{item.name}}"
        uid="{{item.uid}}"
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
        password="{{item.password}}"
  with_items: create_users
  tags: ['users','configuration']

- name: Install oh-my-zsh
  shell: sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  sudo: yes
  sudo_user: "{{ item.username }}"
  with_items: create_users

- name: Add/Update User SSH keys
  authorized_key: user="{{item.0.username}}" key="{{item.1}}"
  with_subelements:
    - create_users
    - ssh_key
  tags: ['users','configuration']

- name: Remove Users
  user: name="{{item.username}}" state=absent
  with_items: remove_users
  tags: ['users','configuration']

- name: Remove user groups
  group: name="{{item.username}}" state=absent
  with_items: remove_users
  when: users_create_per_user_group
  tags: ['groups','configuration']

