---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items: "{{ groups_create }}"
  tags: ['groups', 'configuration']

- name: Remove groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ groups_remove }}"
  tags: ['groups', 'configuration']
