---
- name: Fail2ban package
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Config rsyslog for fail2ban logs
  ansible.builtin.template:
    src: rsyslog-fail2ban.conf
    dest: /etc/rsyslog.d/51-fail2ban.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Rsyslog needs to be reloaded
