- name: install Apache apt packages
  ansible.builtin.apt:
    name:
    - apache2
    state: latest

- name: enable Apache ModSSL
  apache2_module: state=present name=ssl

- name: enable Apache ModRewrite
  apache2_module: state=present name=rewrite
