- name: install Apache apt packages
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items:
   - apache2

- name: enable Apache ModSSL
  apache2_module: state=present name=ssl

- name: enable Apache ModRewrite
  apache2_module: state=present name=rewrite
