- include_vars: 'newrelic.yml'

- name: install PHP apt packages
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items:
   - libapache2-mod-php5
   - composer
   - php5-mysql
   - php5-curl

- name: install NewRelic PHP module
  apt:
    pkg: newrelic-php5
    state: latest
  notify:
    - Run New Relic Installer

- name: create custom PHP config
  template:
    src: rndsvc.ini
    dest: "/etc/php5/mods-available/rndsvc.ini"
    owner: root
    group: root
    mode: 0644
  register: created_rndsvc_php_config

- name: activate custom PHP config
  shell: php5enmod rndsvc
  when: created_rndsvc_php_config.changed
