- name: update Aptitude cache
  apt: update_cache=yes

- name: apt packages
  apt:
    name:
    - aptitude
    - htop
    - vim
    - git
    - git-core
    - haveged
    - openssh-client
    - openssh-server
    state: latest
