---
- name: Update Aptitude cache
  ansible.builtin.apt:
    update_cache: true

- name: Various required packages
  ansible.builtin.apt:
    name:
      - aptitude
      - htop
      - vim
      - git
      - git-core
      - haveged
      - openssh-client
      - openssh-server
    state: present
