---
- name: Aptitude
  ansible.builtin.import_tasks: aptitude.yml
- name: Logrotate
  ansible.builtin.import_tasks: logrotate.yml
- name: ACL
  ansible.builtin.import_tasks: acl.yml
- name: Sysctl
  ansible.builtin.import_tasks: sysctl.yml
- name: Root CA
  ansible.builtin.import_tasks: root_ca.yml
- name: ZSH
  ansible.builtin.import_tasks: zsh.yml
