- name: disable SSH password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "PasswordAuthentication (yes|no)"
  notify:
    - sshd needs to be restarted

- name: enable SSH TCPKeepAlive
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "TCPKeepAlive yes"
    regexp: "TCPKeepAlive (yes|no)"
  notify:
    - sshd needs to be restarted

- name: enable SSH PermitUserEnvironment
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitUserEnvironment yes"
    regexp: "PermitUserEnvironment (yes|no)"
  notify:
    - sshd needs to be restarted

- name: disable root SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: "PermitRootLogin (yes|no)"
  notify:
    - sshd needs to be restarted
