- include_vars: 'sysctl.yml'

- name: configure swappiness
  template: src=10-swappiness.conf dest=/etc/sysctl.d/10-swappiness.conf owner=root group=root mode=0644

- name: set swappiness
  command: "/sbin/sysctl vm.swappiness={{ swappiness }}"
