---
- name: Configure swappiness
  ansible.builtin.template:
    src: 10-swappiness.conf
    dest: /etc/sysctl.d/10-swappiness.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Swappiness changed
